/* eslint-disable no-undef */
// Generated by IcedCoffeeScript 108.0.13
var window = global;
(function () {
  global.make_tab = function (target, spacer) {
    return target.replace(/\n/g, "\n" + spacer);
  };

  global.join_list = function (list, spacer) {
    if (spacer == null) {
      spacer = "";
    }
    return make_tab(list.join("\n"), spacer);
  };
}.call(this));
